### ISSUE TITLE
Fixní ročník v Makefile.inc

### ISSUE THREAD

**Issue by rzehumat** [fykosak/fks-templates#21]
Proč máme v šabloně `templatex/year/Makefile.inc` fixní ročník na `33`?
```
XELATEX_P=xelatex -output-directory $(@D) -jobname '$(basename $(@F))' '\documentclass[fykos]{fkssolution}\setcounter{year}{33}\input{$<}\begin{document}\problemsolutionsingle\makefooter\end{document}'
```

**Comment by sstenchlak** [comment]
Stejně tak `\documentclass[fykos]` by měl být nahrazen zpět na `\documentclass[SEM]`, viz https://github.com/fykosak/fks-scripts/blob/master/scripts/bin/fks-inityear.sh#L70.

Možná otázkou je, používá to někdo? FYKOS totiž už moc ne, protože se nám nevyplatí provádět změny tady i současně v konkrétním repozitáři a snažit se je synchronizovat. Raději kopírujeme repozitář z minulého roku, i když to není nejpěknější řešení. Co Výfuk @Headary?

**Comment by Headary** [comment]
Ve výfuku to používám, převážně z toho důvodu, aby každý rok byl čistý repozitář. Konkrétní větší změny se proto snažím zavést i sem, aby se změny, které byli relevatní pouze pro jeden ročník, nenabalovali postupem času a nebyla polovina věcí v repu zbytečná. Zároveň to usnadňuje init, kdy není třeba vše procházet, měnit ročníky, promazat Makefile, protože většina úloh (takže ani složek) u nás ještě neexistuje na začátku série, atd.

**Comment by rzehumat** [comment]
Krásně řečeno, většinu argumentů bych mohl aplikovat i na FYKOS -- proč kopírování ročníků není dobrá praxe.

**Comment by sstenchlak** [comment]
Já si pamatuji doby, kdy se to dělalo initem a vždy se pak přišlo na něco, co se opravilo v minulém ročníku, ale zapomnělo se to zanést na GH, ale pokud to budeme hlídat, tak to může fungovat :)
